---
title: "Stat388AustraliaProj_Vosburgh"
author: "Stephen Vosburgh"
date: "12/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Data

```{r}
# Import Data
train <- read.csv("train.csv")
test <- read.csv("test.csv")
```


## Data cleanup

```{r}
#data clean
nrow(train)

datetxt <- as.Date(train$date)
df <- data.frame(date = datetxt,
                 year = as.numeric(format(datetxt, format = "%Y")),
                 month = as.numeric(format(datetxt, format = "%m")),
                 day = as.numeric(format(datetxt, format = "%d")))




train$location <- as.factor(train$location)
train$evaporation <- as.factor(train$evaporation)
train$sunshine <- as.factor(train$sunshine)
train$wind_gust_dir <- as.factor(train$wind_gust_dir)
train$wind_dir9am <- as.factor(train$wind_dir9am)
train$wind_dir3pm <- as.factor(train$wind_dir3pm)

train$years <- as.factor(df$year)
train$months <- as.factor(df$month)
train$days <- as.factor(df$day)

train2 <- train

install.packages("Hmisc")
library(Hmisc)

train2$evaporation <- with(train2,impute(evaporation,mode))
train2$sunshine <- with(train2,impute(sunshine,mode))
train2$wind_gust_dir <- with(train2,impute(wind_gust_dir,mode))
train2$wind_dir9am <- with(train2,impute(wind_dir9am,mode))
train2$wind_dir3pm <- with(train2,impute(wind_dir3pm,mode))
train2$wind_dir3pm <- with(train2,impute(wind_dir3pm,mode))
train2$wind_dir3pm <- with(train2,impute(wind_dir3pm,mode))
train2$rainfall <- with(train2,impute(rainfall,mean))
train2$min_temp <- with(train2,impute(min_temp,mean))
train2$max_temp <- with(train2,impute(max_temp,mean))
train2$wind_gust_speed <- with(train2,impute(wind_gust_speed,mean))
train2$wind_speed9am <- with(train2,impute(wind_speed9am,mean))
train2$wind_speed3pm <- with(train2,impute(wind_speed3pm,mean))
train2$humidity9am <- with(train2,impute(humidity9am,mean))
train2$humidity3pm <- with(train2,impute(humidity3pm,mean))
train2$pressure9am <- with(train2,impute(pressure9am,mean))
train2$pressure3pm <- with(train2,impute(pressure3pm,mean))
train2$cloud9am <- with(train2,impute(cloud9am,mean))
train2$cloud3pm <- with(train2,impute(cloud3pm,mean))
train2$temp9am <- with(train2,impute(temp9am,mean))
train2$temp3pm <- with(train2,impute(temp3pm,mean))
train2$rain_today <-  with(train2,impute(rain_today,mean))

# pressure <- 1000.5
# temp <-30.8
# hum <- 69
# cons <- 6.1078 * 10^(7.5*temp /(temp + 237.3))
# 37.57612*52/100
# pv <- cons*hum/100
# dry <- pressure-pv
 rd <- 287.058
# rv <- 461.495
# dens <- dry/(rd*temp) + (pv/(rv+temp))+1
# air_dens <- 
train3 <- train2
train3$density <- (train2$pressure3pm*100)/((train2$temp3pm+273.15)*rd)

summary(train3)
train3 <- train3[,-1]
train3$rain_tomorrow <- as.factor(train3$rain_tomorrow)


datetxt2 <- as.Date(test$date)
df2 <- data.frame(date = datetxt,
                 year2 = as.numeric(format(datetxt, format = "%Y")),
                 month2 = as.numeric(format(datetxt, format = "%m")),
                 day2 = as.numeric(format(datetxt, format = "%d")))


year <- as.factor(df2$year2)
month <- as.factor(df2$month2)
day <- as.factor(df2$day2)
test2 <- test

test2$density <- (test2$pressure3pm*100)/((test2$temp3pm+273.15)*rd)

test2$year <- year
test2$month <- month
test2$day <- day


test2$location <- as.factor(test2$location)
test2$evaporation <- as.factor(test2$evaporation)
test2$sunshine <- as.factor(test2$sunshine)
test2$wind_gust_dir <- as.factor(test2$wind_gust_dir)
test2$wind_dir9am <- as.factor(test2$wind_dir9am)
test2$wind_dir3pm <- as.factor(test2$wind_dir3pm)
test2$rain_today <- as.factor(test2$rain_today)
test2 <- test2[,-1]


test2$evaporation <- with(test2,impute(evaporation,mode))
test2$sunshine <- with(test2,impute(sunshine,mode))
test2$wind_gust_dir <- with(test2,impute(wind_gust_dir,mode))
test2$wind_dir9am <- with(test2,impute(wind_dir9am,mode))
test2$wind_dir3pm <- with(test2,impute(wind_dir3pm,mode))
test2$wind_dir3pm <- with(test2,impute(wind_dir3pm,mode))
test2$wind_dir3pm <- with(test2,impute(wind_dir3pm,mode))
test2$rain_today <-  with(test2,impute(rain_today,mode))
test2$rainfall <- with(test2,impute(rainfall,mean))
test2$min_temp <- with(test2,impute(min_temp,mean))
test2$max_temp <- with(test2,impute(max_temp,mean))
test2$wind_gust_speed <- with(test2,impute(wind_gust_speed,mean))
test2$wind_speed9am <- with(test2,impute(wind_speed9am,mean))
test2$wind_speed3pm <- with(test2,impute(wind_speed3pm,mean))
test2$humidity9am <- with(test2,impute(humidity9am,mean))
test2$humidity3pm <- with(test2,impute(humidity3pm,mean))
test2$pressure9am <- with(test2,impute(pressure9am,mean))
test2$pressure3pm <- with(test2,impute(pressure3pm,mean))
test2$cloud9am <- with(test2,impute(cloud9am,mean))
test2$cloud3pm <- with(test2,impute(cloud3pm,mean))
test2$temp9am <- with(test2,impute(temp9am,mean))
test2$temp3pm <- with(test2,impute(temp3pm,mean))
summary(train3)
train3
summary(test2)
a4 <- (predict(a,newdata=test2,type="response"))


(6050+1159)/((808+531)+(6050+1159))
a <- randomForest(rain_tomorrow ~ ., data=trains,importance=TRUE )
a2<- randomForest(rain_tomorrow ~ ., data=train3,importance=TRUE )
summary(a2)
a2$predicted
plot(a2$importance)
a5 <- (predict(a2,newdata=test2,type="response"))
table(a5, tests$rain_tomorrow)
predictions <- data.frame(id = test$id,rain_tomorrow = a5)
predictions
importance(a2)
write.csv(predictions,"C:\\Users\\akhil\\Desktop\\predictions4.csv", row.names = FALSE)

```

